#!/bin/bash
# テンプレート削除スクリプト（ローカル開発環境用）

echo "==================================="
echo "テンプレートデータ削除スクリプト"
echo "（ローカル開発環境用）"
echo "==================================="
echo ""

echo "📊 ステップ1: 現在のデータ件数を確認"
echo "-----------------------------------"
echo "🔍 テンプレート数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM templates"
echo ""
echo "🔍 フォーム数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM forms"
echo ""
echo "🔍 見積書数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM quotes"
echo ""
echo "🔍 テンプレートフィールド数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM template_fields"
echo ""

echo "🗑️  ステップ2: テンプレートデータを削除"
echo "-----------------------------------"
npx wrangler d1 execute webapp-production --local --command="DELETE FROM templates"
echo "✅ テンプレートを削除しました"
echo ""

echo "🔄 ステップ3: ユーザーのテンプレート作成数をリセット"
echo "-----------------------------------"
npx wrangler d1 execute webapp-production --local --command="UPDATE users SET templates_created = 0"
echo "✅ ユーザーのカウンターをリセットしました"
echo ""

echo "📊 ステップ4: 削除後のデータ件数を確認"
echo "-----------------------------------"
echo "🔍 テンプレート数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM templates"
echo ""
echo "🔍 フォーム数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM forms"
echo ""
echo "🔍 見積書数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM quotes"
echo ""
echo "🔍 テンプレートフィールド数:"
npx wrangler d1 execute webapp-production --local --command="SELECT COUNT(*) as count FROM template_fields"
echo ""

echo "==================================="
echo "✅ 削除処理が完了しました"
echo "==================================="
